/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 iphone.gltf --transform
Author: rajatnidaria (https://sketchfab.com/rajatnidaria)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/apple-iphone-11-max-pro-free-92efa21badc94807bbe1cd0a22e6b6da
Title: Apple Iphone 11 max pro [ FREE ]
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/iphone-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
          <group position={[0, 7.51, -0.2]} rotation={[1.58, 0, 0]}>
            <mesh geometry={nodes.polySurface34_blinn22_0.geometry} material={materials.blinn22} position={[0, -0.05, 0]} />
            <mesh geometry={nodes.polySurface38_blinn24_0.geometry} material={materials.blinn24} />
            <mesh geometry={nodes.polySurface39_blinn17_0.geometry} material={materials.blinn17} />
            <mesh geometry={nodes.polySurface40_blinn31_0.geometry} material={materials.blinn31} />
            <mesh geometry={nodes.polySurface42_blinn18_0.geometry} material={materials.blinn18} />
            <mesh geometry={nodes.polySurface45_blinn23_0.geometry} material={materials.blinn23} />
            <mesh geometry={nodes.polySurface53_blinn32_0.geometry} material={materials.blinn32} position={[0, -0.02, 0]} />
            <mesh geometry={nodes.polySurface61_blinn30_0.geometry} material={materials.blinn30} />
          </group>
          <mesh geometry={nodes.polySurface64_blinn21_0.geometry} material={materials.blinn21} />
          <mesh geometry={nodes.polySurface48_blinn33_0.geometry} material={materials.blinn33} />
          <mesh geometry={nodes.polySurface55_blinn35_0.geometry} material={materials.blinn35} />
          <mesh geometry={nodes.polySurface63_blinn36_0.geometry} material={materials.blinn36} />
          <mesh geometry={nodes.polySurface36_blinn26_0.geometry} material={materials.blinn26} />
          <mesh geometry={nodes.polySurface50_blinn34_0.geometry} material={materials.blinn34} />
          <mesh geometry={nodes.polySurface60_blinn25_0.geometry} material={materials.blinn25} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/iphone-transformed.glb')
